# a few key numpy functionalities

In [34]:
import numpy as np

In [35]:
# returns a range of values (stop, start, by)
np.arange(0,25,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [30]:
# rehsape an array into whatever dimensions you prefer. arr len needs to be equal to RxC
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## numpy has its own library of 'random' functionalities

In [6]:
# returns an array sampled from a uniform [0,1) distribution
# parameters are just integers which specify the dimension of the array
np.random.rand(5,5)

array([[0.42630906, 0.95860363, 0.35648776, 0.59787204, 0.41475011],
       [0.45226081, 0.6629826 , 0.87670986, 0.37583117, 0.37180994],
       [0.64846002, 0.88940441, 0.61151466, 0.06392212, 0.37921736],
       [0.70820924, 0.23145065, 0.25701777, 0.19361033, 0.31886887],
       [0.21197444, 0.93739953, 0.90980976, 0.4539825 , 0.86611471]])

In [7]:
# reutrns array from standard normal distribution
np.random.randn(5,5)

array([[ 1.83766062, -0.88910577, -0.6843299 , -1.24520933,  0.00744178],
       [ 0.58898323,  0.69554783, -0.85726613,  1.12738692,  0.18896729],
       [ 0.06572242, -1.06790734, -0.42969823, -0.3575806 , -0.47596191],
       [ 1.43404038,  0.25902121,  1.31601972,  0.51447563, -0.48534696],
       [-0.35277959, -0.05809634,  0.12122169,  1.78970056, -1.24657901]])

In [25]:
# returns random integers from uniform distribution specified by user. pass a tuple to make it a matrix of size RxC
np.random.randint(0,101,(5,5))

# lower/upper bounds can be lists. this returns three numbers with 3 different lower bounds (upper bound is 15)
np.random.randint([9,8,7], 15)

# this returns three numbers: one number between 9 and 10, another between 8 and 11, and another between 7 and 12
np.random.randint([9,8,7],[10,11,12])

# can return a matrix by broadcasting
np.random.randint([2,4,6,8],[[15],[30]])

array([[11,  9, 13, 11],
       [ 2,  8, 20, 15]])

In [33]:
# seed setting
# seed will only work if rest of code is in the same cell
np.random.seed(42)
np.random.randint(0,5,(5,5))

array([[3, 4, 2, 4, 4],
       [1, 2, 2, 2, 4],
       [3, 2, 4, 1, 3],
       [1, 3, 4, 0, 3],
       [1, 4, 3, 0, 0]])